# -*- coding: utf-8 -*-
"""8_19301051_Kazi Md. Al-Wakil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nxG-ZLwHxQMyza-O4BL4cZHMOTua1pzC
"""

from google.colab import drive
drive.mount('/content/drive')

# lab 1 Task 1
# Question 1 
# Corona Infected, Total Infected in a area, Using DFS

t1Openkori = open("/content/drive/MyDrive/CSE422 Labs/Task_1_input_1.txt","r")
inpThekeNiyeStr = t1Openkori.readlines() #storing the inputs line by line
asholMtrxList = [] #matrix akare store korbo sob input gulake. nsted ekta list hobe ei list e 


#Matrix list banacchi ekhane

for xqxItar1 in inpThekeNiyeStr:
  if xqxItar1[-1]!="\n": #last e ekta line break ache. jodi line break  na thake tahole amra normally split korbo
    xqxTempLis = xqxItar1.split()
  else:
    xqxTempLis = xqxItar1[:-1].split() # jodi line break thake tahole amra line break er ag porrjonto slip kore ekta temp list e rakhbo
  
  borobhailanght = len(xqxTempLis) #lenght ber korbo
  for xqxItar2 in range(borobhailanght): #lenght borabor ghurabo, list er bhitore prottek ta list k dhore 1,0 banabo
    if xqxTempLis[xqxItar2] == "Y": # Y paile 1 banabo
      xqxTempLis [xqxItar2] = 1
    elif xqxTempLis[xqxItar2] == "N": # N paile 0 banabo
      xqxTempLis[xqxItar2] = 0
  asholMtrxList.append(xqxTempLis) #1,0 diye j list banaisi, seta k amader main jei list sekhane append kore dilam
#---------------------
asholDic ={} # ei dic e adjucant lst banabo. kon node theke kon node jaitese tar hisab thakbe

asholCountTotalInfcted = 0 #total koto manush er moddhe corona chorailo, kon area te sob cheye beshi chorailo tar hisab eikhane rakhbo

innertempoList = asholMtrxList[0] #nested list er bhitor joto gula iteam ache, segula hoitese amader colum number
xqxlenghtRow = len(asholMtrxList) #main list er bhitor j koyta list ache, segula amader row number
xqxlenghtColam = len(innertempoList)

for rowBorabor in range(xqxlenghtRow):
  for colamBorabor in range(xqxlenghtColam):
    if asholMtrxList[rowBorabor][colamBorabor]==1:

      bortomaneKinfcted = (rowBorabor * xqxlenghtColam) + colamBorabor # 1 gula kon kon position e ache ta ber korlam.
      if bortomaneKinfcted not in asholDic:
        asholDic[bortomaneKinfcted] = [] #dictionary create korlam. dictionary te key hisabe 1 gular position ache
                                         
#-------------------------------------------------Shuru-------------------------------------------------------------

      if rowBorabor < (xqxlenghtRow-1) and asholMtrxList[rowBorabor + 1][colamBorabor] == 1:
        neighborInfctd = ((rowBorabor + 1) * xqxlenghtColam) + colamBorabor

        if neighborInfctd not in asholDic:
          asholDic[neighborInfctd] = []
        asholDic[bortomaneKinfcted].append(neighborInfctd)
        asholDic[neighborInfctd].append(bortomaneKinfcted) #kono node theke upore ba niche jawa jay kina dekhtesi

#-------------------------------------------------Cholche-------------------------------------------------------------

      if colamBorabor < (xqxlenghtColam-1) and asholMtrxList[rowBorabor][colamBorabor+1] == 1:
        neighborInfctd = (rowBorabor * xqxlenghtColam) + colamBorabor + 1

        if neighborInfctd not in asholDic:
          asholDic[neighborInfctd] = []
        asholDic[bortomaneKinfcted].append(neighborInfctd)
        asholDic[neighborInfctd].append(bortomaneKinfcted) #side e kono node ache kina check kortesi

#-------------------------------------------------Cholche-------------------------------------------------------------
      if rowBorabor < (xqxlenghtRow-1) and asholMtrxList[rowBorabor+1][colamBorabor-1] == 1:
        neighborInfctd = ((rowBorabor + 1) * xqxlenghtColam) + (colamBorabor - 1)

        if neighborInfctd not in asholDic:
          asholDic[neighborInfctd] = []
        asholDic[bortomaneKinfcted].append(neighborInfctd) 
        asholDic[neighborInfctd].append(bortomaneKinfcted)  #Bam dike konakoni 1 pacchi kina dekhtesi

#-------------------------------------------------Cholche-------------------------------------------------------------

      if rowBorabor < (xqxlenghtRow-1) and colamBorabor < (xqxlenghtColam-1) and asholMtrxList[rowBorabor+1][colamBorabor+1] == 1:
        neighborInfctd = ((rowBorabor + 1) * xqxlenghtColam) + (colamBorabor + 1)

        if neighborInfctd not in asholDic:
          asholDic[neighborInfctd] = []
        asholDic[bortomaneKinfcted].append(neighborInfctd)
        asholDic[neighborInfctd].append(bortomaneKinfcted) #dan dike konakoni 1 pacchi kina dekhtesi
#-------------------------------------------------Khotom-------------------------------------------------------------      

asholMtrxList_dup = []
for i_xqx1 in asholMtrxList:
  for i_xqx2 in i_xqx1:
    asholMtrxList_dup.append(i_xqx2) # Ekta temporary matrx banailam, jekhane amar ashol matrix er sob content rakha ache. duplicate matrx bola jay, 
    # duplicate matrix er er proti node visit kora hobe,ekbar visit kore -1 kore dibo sei node k. 


#-------------------------------------------------Shuru-------------------------------------------------------------   
def dqfxsBro (infctdNdes, koriAmraCount):
  asholMtrxList_dup[infctdNdes] = -1 #jehetu visit korsi, tai -1 kore dilam
  koriAmraCount = koriAmraCount+1 # koto jon infcted eta ber korbo ei var diya
  for i_xqx1 in asholDic[infctdNdes]:

    if asholMtrxList_dup[i_xqx1] == 1: #1 hole to visited na. taile dfs chalabo oi node er upor
      koriAmraCount = dqfxsBro(i_xqx1,koriAmraCount)
  return koriAmraCount
#-------------------------------------------------Khotom-------------------------------------------------------------  


for i_xqx1key in asholDic.keys():
  dfsthekepawavalue = dqfxsBro(i_xqx1key, 0) #Node pathailam r, sathe count korar jonno ekta number pathailam. number shuru 0 theke. 
  if dfsthekepawavalue > asholCountTotalInfcted:
    asholCountTotalInfcted = dfsthekepawavalue #highest val ta e rakha hobe

print("Max people infected in a region: ",asholCountTotalInfcted) 

#Done

t1Openkori.close

# lab 1 Task 2
# Question 2 
# There is an Alien(Xenomorph) Apocalypse in XCITY and every minute Aliens are attacking human beings around them......
# Using BFS
t2Openkori = open("/content/drive/MyDrive/CSE422 Labs/Task_2_input_1.txt","r")
inpThekeNiyeStr = t2Openkori.readlines() #storing the inputs line by line

asholMtrxList = [] #matrix akare store korbo sob input gulake. nsted ekta list hobe ei list e 
noNeedCnt = 0
#Matrix list banacchi ekhane
for xqxItar1 in inpThekeNiyeStr:

  if xqxItar1[-1]!="\n": #last e ekta line break ache. jodi line break  na thake tahole amra normally split korbo
    xqxTempLis = xqxItar1.split()
  else:
    xqxTempLis = xqxItar1[:-1].split() # jodi line break thake tahole amra line break er ag porrjonto slip kore ekta temp list e rakhbo


  if noNeedCnt == 0:
    temp_row = int(xqxTempLis[0]) #temp_row koyta ber korchi
    noNeedCnt+=1
  elif noNeedCnt == 1:
    temp_colam = int(xqxTempLis[0]) #Colam koyta ber korchi
    noNeedCnt+=1
  else:
    borobhailanght = len(xqxTempLis) #lenght ber korbo
    for xqxItar2 in range(borobhailanght): #lenght borabor ghurabo, list er bhitore prottek ta list k dhore 1,0 banabo
      if xqxTempLis[xqxItar2] == "A": # Allien paile -1 banabo
        xqxTempLis [xqxItar2] = -1
      elif xqxTempLis[xqxItar2] == "H": # Human paile 0 banabo
        xqxTempLis[xqxItar2] = 0
    asholMtrxList.append(xqxTempLis) #1,0 diye j list banaisi, seta k amader main jei list sekhane append kore dilam. ekta nested list hoilo

asholRow = temp_row #raw store korlam
asholColam = temp_colam #colam store korlam
#--------------------- 
humLifeCnt = 0 #total koyjon survivar ache, ei variable diye check korbo
alirActualPos = [] #alien der pasiton gula tuple akare ei list e rakhbo. time to time update korbo
shomoy = 0 #total time 

#-------------------------------------------------Def shuru---------------------------------------------------
def humAndAlirPos():
  global humLifeCnt 
  for ab in range(asholRow):
    for cd in range(asholColam):
      if asholMtrxList[ab][cd] == 0:
        humLifeCnt = humLifeCnt +1 #jokhon e kono human pabo, take initial sarvivor var er sathe add kore dibo. ei var theke amra total sarvivor koto jon ache ta bujhte parbo
      elif asholMtrxList[ab][cd] == -1:
        alirActualPos.append((ab,cd)) #alien der postion matrix er kon pos e ache, seta tuple akare rakhbo.
humAndAlirPos() 
#-------------------------------------------------Def khotom--------------------------------------------------


#-------------------------------------------------Def shuru---------------------------------------------------
def bqfxsBro():
  global humLifeCnt
  global alirActualPos
  global shomoy
  alirTempPos = [] #ekta temporary list. ekhane per time e koto jon human k alien banano hoilo, newly alien howader pos niye ekta tuple ei list e append hobe. 
  while len(alirActualPos):
    algaTemp = alirActualPos.pop(0)
    r_Wise = algaTemp[0]
    col_Wise = algaTemp[1]
    #---------------------------------------------Checking shuru--------------------------------------------------
    #top to bottom e kono alien ache kina dekhtesi
    if (r_Wise-1 >= 0) and (col_Wise <= asholColam-1) and asholMtrxList[r_Wise-1][col_Wise] == 0: #top e kono human ache kina dekhtesi
      asholMtrxList[r_Wise-1][col_Wise] = -1 #visit kora done, tai -1 kore dicchi
      alirTempPos.append((r_Wise-1,col_Wise)) #top e thaka human k alien baniye, tar position diye dilam tempo list e
      humLifeCnt = humLifeCnt - 1 #sarvivor komtese
    if (r_Wise+1 <= asholRow-1) and (col_Wise <= asholColam-1) and asholMtrxList[r_Wise+1][col_Wise] == 0: #bottom e kono human ache kina dekhtesi
      asholMtrxList[r_Wise+1][col_Wise] = -1 #visit kora done, tai -1 kore dicchi
      alirTempPos.append((r_Wise+1,col_Wise)) #bottom e thaka human k alien baniye, tar position diye dilam tempo list e
      humLifeCnt = humLifeCnt - 1 #sarvivor komtese
    
    #---------------------------------------------Checking shuru--------------------------------------------------

    #right  to left e kono alien ache kina dekhtesi
    if (r_Wise <= asholRow-1) and (col_Wise+1 <= asholColam-1) and asholMtrxList[r_Wise][col_Wise+1] == 0: #right e kono human ache kina dekhtesi
      asholMtrxList[r_Wise][col_Wise+1] = -1 #visit kora done, tai -1 kore dicchi
      alirTempPos.append((r_Wise,col_Wise+1)) #right e thaka human k alien baniye, tar position diye dilam tempo list e
      humLifeCnt = humLifeCnt - 1 #sarvivor komtese
    if (r_Wise <= asholRow-1) and (col_Wise-1 >=0) and asholMtrxList[r_Wise][col_Wise-1] == 0: #left e kono human ache kina dekhtesi
      asholMtrxList[r_Wise][col_Wise-1] = -1 #visit kora done, tai -1 kore dicchi
      alirTempPos.append((r_Wise,col_Wise-1)) #left e thaka human k alien baniye, tar position diye dilam tempo list e
      humLifeCnt = humLifeCnt - 1  #sarvivor komtese  
    #---------------------------------------------Checking Khotom-------------------------------------------------------------  
  lenghtTempPos = len(alirTempPos) 
  if lenghtTempPos > 0: #jodi temp list "alirTempPos" e kono tuple thake, 
    alirActualPos = alirTempPos #tahole notun alien howa human gular pos amra copy korbo amader actual alien der postion e. karon puran postion diye amra kaj kore felsi
                                # ekhon notun jara alien hoise, tader theke kon human alien hoite parbe seta amra ber korbo, tar jonno copy kore dilam amader main list e.
    shomoy = shomoy +1  #ekbar hum der alien banano hoye gele, amra somoy ek kore baray dibo. 

    
#-------------------------------------------------Def Khotom-------------------------------------------------------------  

while len(alirActualPos): #loop ta cholbe, jotokhon porjonto amader alien er position er jonno dedicated list ta faka na hoy. 
                          #faka howa mane amader alienpostion list e emon kono alien nai, jar dara kono human alien hoite parbe. sob possible human k alein banano sesh
                          #tokhon amra bfs r chalabo na. loop break hobe. 
  bqfxsBro()



print("Time: ", shomoy, "minutes.") 
if humLifeCnt <=0: #human count jodi 0 or 0 er theke kom hoy, tar mane keu beche nai. sob dead
 print("No one Survived.") 
else:
  print(humLifeCnt, "survived.")
#Done

t2Openkori.close

